name: Docker Image CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test -v ./...

            # Запуск тестовой базы данных PostgreSQL
            - name: Start PostgreSQL container
              run: |
                  docker network create test-network || true
                  docker run --name test-postgres --network test-network -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -e POSTGRES_DB=testdb -d postgres:15
                  sleep 10

            # Выполнение миграций на тестовой базе
            - name: Run database migrations
              run: |
                  docker run --rm --network test-network -v $(pwd)/migrations:/migrations migrate/migrate \
                    -path=/migrations -database postgres://test:test@test-postgres:5432/testdb?sslmode=disable up

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-shortener:latest
    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      # Загружаем переменные окружения из .env файла
                      cd app
                      set -o allexport
                      source .env || echo ".env file not found"
                      set +o allexport

                      # Проверка, установилась ли переменная DATABASE_URL
                      echo "Database URL: $DATABASE_URL"

                      # Остановить только backend контейнер
                      docker-compose stop backend

                      # Выкачать новый образ для backend
                      docker-compose pull backend

                      # Запустить миграции
                      docker run --rm --network host -v /path/to/migrations:/migrations smakasaki/go-shortener \
                        migrate -path=/migrations -database $DATABASE_URL up

                      # Перезапустить только backend
                      docker-compose up -d backend
