name: Migrate

on:
    workflow_dispatch:

jobs:
    migrate:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Migrate database
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ~/app
                      make migrate-up
